<a href="https://colab.research.google.com/github/digogc/Python-para-Data-Science/blob/main/Utilizando_Pandas/Diferentes_tipos_de_Arquivos/Desafios.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Importando o Pandas
import pandas as pd

# Salvando a URL
url = 'https://raw.githubusercontent.com/alura-cursos/Pandas/main/dados_sus.csv'

In [ ]:
# Lendo o arquivo
# Separador é a vírgula
# O enconding é ISO-8859-1
# As primeiras 3 linhas devem ser desconsideradas
# As últimas 9 linhas devem ser desconsideradas
# Quando as últimas linhas são separadas, é necessário selecionar a engine (Python)
dados_sus = pd.read_csv(url, sep=';', encoding='ISO-8859-1', skiprows=3, skipfooter=9, engine='python')
dados_sus

Unidade da Federação      2008/Jan      2008/Fev      2008/Mar  \
0              Rondônia    1388528,39    2931283,42    1541682,52   
1                  Acre     902416,00    1497206,26    1794028,48   
2              Amazonas    4735529,42    7118990,57    8196635,49   
3               Roraima     657889,53     777939,31     718688,03   
4                  Pará   18864744,11   19553758,20   21937342,70   
5                 Amapá    1120973,34    1268740,33     974651,24   
6             Tocantins    3441592,69    4985688,85    6205612,60   
7              Maranhão   10723506,39   13559679,41   13985142,36   
8                 Piauí    7985142,43   10079928,25   10298372,45   
9                 Ceará   15539821,90   25735101,55   28724625,75   
10  Rio Grande do Norte    5947814,08    9509755,83   10352238,59   
11              Paraíba   10723002,45   11386274,47   12053643,87   
12           Pernambuco   14393949,89   24181400,95   29991302,71   
13              Alagoas    6243726,32    8376622,16    8408336,22   
14              Sergipe    2780750,11    3676483,16    5051473,61   
15                Bahia   21211522,47   28189304,95   34181483,52   
16         Minas Gerais   45671659,76   70194037,10   79231336,95   
17       Espírito Santo    5456723,98    9102212,86   10249595,97   
18       Rio de Janeiro   23025258,52   28394310,93   44567062,94   
19            São Paulo   91678473,48  148677526,82  156087269,23   
20               Paraná   38266347,46   55384670,52   53801318,85   
21       Santa Catarina   16504913,45   25651429,11   26743524,89   
22    Rio Grande do Sul   30931325,46   57363420,01   51547794,07   
23   Mato Grosso do Sul    5377392,11    7002472,61    8423933,19   
24          Mato Grosso    4795299,01    8684882,23    7886243,14   
25                Goiás   15310637,29   22258668,68   21442515,75   
26     Distrito Federal    4745919,19    7632480,67    9647203,26   
27                Total  408424859,23  613174269,21  664043058,38   

        2008/Abr      2008/Mai      2008/Jun      2008/Jul      2008/Ago  \
0     1525314,96    1645953,84    1406150,68    3065279,01    3231494,61   
1     1730469,42    1819443,92    1828496,00    2511754,59    2089107,14   
2     8259378,42    7831399,90    8477273,62    9368858,72    9352532,70   
3      839994,39     862347,96     832440,66     996693,09     894271,18   
4    20842829,69   23249952,88   23240687,56   24002223,56   23341218,03   
5     1141137,32     866346,18    1440978,95    1426659,48    1475551,38   
6     4984482,09    5511002,46    4927934,22    5445602,28    5413710,38   
7    14809416,46   14505727,38   14908091,32   15784899,40   15195312,89   
8    10775976,33   10398360,88   10528253,88   11040107,92   10549176,40   
9    30676457,06   30604453,47   31272395,18   30925391,36   27851438,72   
10   10855108,50   11160168,19   10475071,38   11386349,96   10640817,47   
11   12653528,76   12215107,11   12256928,49   12755413,77   12872578,37   
12   34806197,97   32147987,35   32239094,89   32685640,76   35457038,66   
13    9090794,82    9338771,45   10068210,08    9887061,61    9373432,00   
14    5046063,36    4741151,56    5401259,63    5521904,44    5238398,50   
15   39026934,13   42949566,82   47025972,04   47481695,17   46931248,28   
16   77136537,58   80554440,63   94758522,83   85360064,11   84722528,10   
17   11253833,56   10198619,17   13364258,29   13035374,08   12588595,77   
18   44054604,82   44911021,15   48056212,24   49872379,35   50912706,60   
19  161227125,43  187119397,64  187291126,07  194398399,48  184854516,35   
20   52460306,69   54419620,71   57811688,48   58094241,83   56982774,90   
21   27181488,26   26845308,18   29909762,04   30789135,84   31250854,33   
22   56673338,49   48397733,07   52413429,62   56636376,98   56113054,70   
23    8797487,68    9770421,80   10905392,18   10249299,82    9671553,45   
24    8794109,79    9231645,40   10221763,77    9163314,28    9243148,81   
25   20921212,45   216159

## Desafio Utilizando API

In [ ]:
# importando as bibliotecas necessárias
import requests
import json

In [ ]:
# realizando a requisição
dados_usuarios = requests.get('https://jsonplaceholder.typicode.com/users')
resultado = json.loads(dados_usuarios.text)

In [ ]:
# transformando em um df
dados_usuarios_normalizado = pd.json_normalize(resultado, sep='_')

In [ ]:
# visualizando o df
dados_usuarios_normalizado

id                      name          username                      email  \
0   1             Leanne Graham              Bret          Sincere@april.biz   
1   2              Ervin Howell         Antonette          Shanna@melissa.tv   
2   3          Clementine Bauch          Samantha         Nathan@yesenia.net   
3   4          Patricia Lebsack          Karianne  Julianne.OConner@kory.org   
4   5          Chelsey Dietrich            Kamren   Lucio_Hettinger@annie.ca   
5   6      Mrs. Dennis Schulist  Leopoldo_Corkery    Karley_Dach@jasper.info   
6   7           Kurtis Weissnat      Elwyn.Skiles     Telly.Hoeger@billy.biz   
7   8  Nicholas Runolfsdottir V     Maxime_Nienow       Sherwood@rosamond.me   
8   9           Glenna Reichert          Delphine    Chaim_McDermott@dana.io   
9  10        Clementina DuBuque    Moriah.Stanton     Rey.Padberg@karina.biz   

                   phone        website     address_street address_suite  \
0  1-770-736-8031 x56442  hildegard.org        Kulas Light      Apt. 556   
1    010-692-6593 x09125  anastasia.net      Victor Plains     Suite 879   
2         1-463-123-4447    ramiro.info  Douglas Extension     Suite 847   
3      493-170-9623 x156       kale.biz        Hoeger Mall      Apt. 692   
4          (254)954-1289   demarco.info       Skiles Walks     Suite 351   
5   1-477-935-8478 x6430        ola.org  Norberto Crossing      Apt. 950   
6           210.067.6132       elvis.io          Rex Trail     Suite 280   
7      586.493.6943 x140   jacynthe.com   Ellsworth Summit     Suite 729   
8   (775)976-6794 x41206     conrad.com         Dayna Park     Suite 449   
9           024-648-3804    ambrose.net    Kattie Turnpike     Suite 198   

     address_city address_zipcode address_geo_lat address_geo_lng  \
0     Gwenborough      92998-3874        -37.3159         81.1496   
1     Wisokyburgh      90566-7771        -43.9509        -34.4618   
2   McKenziehaven      59590-4157        -68.6102        -47.0653   
3     South Elvis      53919-4257         29.4572       -164.2990   
4      Roscoeview           33263        -31.8129         62.5342   
5   South Christy      23505-1337        -71.4197         71.7478   
6       Howemouth      58804-1099         24.8918         21.8984   
7       Aliyaview           45169        -14.3990       -120.7677   
8  Bartholomebury      76495-3109         24.6463       -168.8889   
9     Lebsackbury      31428-2261        -38.2386         57.2232   

         company_name                       company_catchPhrase  \
0     Romaguera-Crona    Multi-layered client-server neural-net   
1        Deckow-Crist            Proactive didactic contingency   
2  Romaguera-Jacobson         Face to face bifurcated interface   
3       Robel-Corkery  Multi-tiered zero tolerance productivity   
4         Keebler LLC      User-centric fault-tolerant solution   
5   Considine-Lockman        Synchronised bottom-line interface   
6         Johns Group        Configurable multimedia task-force   
7     Abernathy Group             Implemented secondary concept   
8       Yost and Sons     Switchable contextually-based project   
9          Hoeger LLC         Centralized empowering task-force   

                             company_bs  
0           harness real-time e-markets  
1      synergize scalable supply-chains  
2       e-enable strategic applications  
3  transition cutting-edge web services  
4      revolutionize end-to-end systems  
5      e-enable innovative applications  
6         generate enterprise e-tailers  
7         e-enable extensible e-tailers  
8      aggregate real-time technologies  
9              target end-to-end models

# Desafio Extraindo tabela da Wikipedia

Primeiro é necessário realizar o upload do arquivo no colab

In [ ]:
# lendo o arquivo
dados_html = pd.read_html('/content/populacoes.html')

# visualizando a lista de tabelas
dados_html

[     Unnamed: 0 Posição    País (ou território dependente) Estimativa da ONU  \
 0           NaN       1                              Índia     1 429 921 746   
 1           NaN       2                              China     1 426 391 281   
 2           NaN       3                     Estados Unidos       346 353 341   
 3           NaN       4                          Indonésia       277 184 719   
 4           NaN       5                          Paquistão       240 215 932   
 ..          ...     ...                                ...               ...   
 245         NaN       –     Ilha de Ascensão (Reino Unido)             1 100   
 246         NaN     195                           Vaticano               879   
 247         NaN       –  Ilhas Cocos (Keeling) (Austrália)               605   
 248         NaN       –     Tristão da Cunha (Reino Unido)               264   
 249         NaN       –       Ilhas Pitcairn (Reino Unido)                67   
 
     Crescimento desde a ú

In [ ]:
# Salvando a tabela de interesse
populacoes = dados_html[0]

# Visualizando o df
populacoes

Unnamed: 0 Posição    País (ou território dependente) Estimativa da ONU  \
0           NaN       1                              Índia     1 429 921 746   
1           NaN       2                              China     1 426 391 281   
2           NaN       3                     Estados Unidos       346 353 341   
3           NaN       4                          Indonésia       277 184 719   
4           NaN       5                          Paquistão       240 215 932   
..          ...     ...                                ...               ...   
245         NaN       –     Ilha de Ascensão (Reino Unido)             1 100   
246         NaN     195                           Vaticano               879   
247         NaN       –  Ilhas Cocos (Keeling) (Austrália)               605   
248         NaN       –     Tristão da Cunha (Reino Unido)               264   
249         NaN       –       Ilhas Pitcairn (Reino Unido)                67   

    Crescimento desde a última estimativa      Estimativa Oficial  
0                            +269.108.746      Estimativa oficial  
1                             +87.778.313           Censo oficial  
2                             +31.241.565           Censo oficial  
3                             +33.168.546      Estimativa oficial  
4                             +65.636.932      Estimativa oficial  
..                                    ...                     ...  
245                                   NaN  Estimativa oficial[10]  
246                                   NaN      Estimativa oficial  
247                                   NaN      Estimativa oficial  
248                                   NaN  Estimativa oficial[11]  
249                                   NaN      Estimativa oficial  

[250 rows x 6 columns]

In [ ]:
# Excluindo a coluna do df que não agrega informação
populacoes = populacoes.drop(columns=['Unnamed: 0'])

In [ ]:
# Visualizando novamente
populacoes

Posição    País (ou território dependente) Estimativa da ONU  \
0         1                              Índia     1 429 921 746   
1         2                              China     1 426 391 281   
2         3                     Estados Unidos       346 353 341   
3         4                          Indonésia       277 184 719   
4         5                          Paquistão       240 215 932   
..      ...                                ...               ...   
245       –     Ilha de Ascensão (Reino Unido)             1 100   
246     195                           Vaticano               879   
247       –  Ilhas Cocos (Keeling) (Austrália)               605   
248       –     Tristão da Cunha (Reino Unido)               264   
249       –       Ilhas Pitcairn (Reino Unido)                67   

    Crescimento desde a última estimativa      Estimativa Oficial  
0                            +269.108.746      Estimativa oficial  
1                             +87.778.313           Censo oficial  
2                             +31.241.565           Censo oficial  
3                             +33.168.546      Estimativa oficial  
4                             +65.636.932      Estimativa oficial  
..                                    ...                     ...  
245                                   NaN  Estimativa oficial[10]  
246                                   NaN      Estimativa oficial  
247                                   NaN      Estimativa oficial  
248                                   NaN  Estimativa oficial[11]  
249                                   NaN      Estimativa oficial  

[250 rows x 5 columns]

# Desafio criando um banco de dados

In [ ]:
# importando a biblioteca sqlalchemy e os métodos que serão necessários
import sqlalchemy
from sqlalchemy import create_engine, MetaData, Table, inspect

In [ ]:
# Salvando o salvando o arquivo csv como um df
url = 'https://raw.githubusercontent.com/alura-cursos/Pandas/main/clientes_banco.csv'
dados = pd.read_csv(url)

dados.head()

ID_Cliente  Idade Grau_escolaridade   Estado_civil  Tamanho_familia  \
0     5008804     32   Ensino superior  União-estável                2   
1     5008805     32   Ensino superior  União-estável                2   
2     5008806     58      Ensino médio         Casado                2   
3     5008808     52      Ensino médio       Solteiro                1   
4     5008809     52      Ensino médio       Solteiro                1   

    Categoria_de_renda   Ocupacao  Anos_empregado  Rendimento_anual  \
0            Empregado      Outro              12          427500.0   
1            Empregado      Outro              12          427500.0   
2            Empregado  Segurança               3          112500.0   
3  Associado comercial     Vendas               8          270000.0   
4  Associado comercial     Vendas               8          270000.0   

   Tem_carro                   Moradia  
0          1       Apartamento alugado  
1          1       Apartamento alugado  
2          1  Casa/apartamento próprio  
3          0  Casa/apartamento próprio  
4          0  Casa/apartamento próprio

In [ ]:
# Criando um banco de dados
engine = create_engine('sqlite:///:memory:')

In [ ]:
# Movendo os dados do df para o banco de dados
dados.to_sql('clientes', engine, index=False)

438463

In [ ]:
# criando um inspector para conseguir obter dados do bd
inspector = inspect(engine)

# Verificando se a tabela foi criada corretamente
print(inspector.get_columns('clientes'))

[{'name': 'ID_Cliente', 'type': BIGINT(), 'nullable': True, 'default': None, 'primary_key': 0}, {'name': 'Idade', 'type': BIGINT(), 'nullable': True, 'default': None, 'primary_key': 0}, {'name': 'Grau_escolaridade', 'type': TEXT(), 'nullable': True, 'default': None, 'primary_key': 0}, {'name': 'Estado_civil', 'type': TEXT(), 'nullable': True, 'default': None, 'primary_key': 0}, {'name': 'Tamanho_familia', 'type': BIGINT(), 'nullable': True, 'default': None, 'primary_key': 0}, {'name': 'Categoria_de_renda', 'type': TEXT(), 'nullable': True, 'default': None, 'primary_key': 0}, {'name': 'Ocupacao', 'type': TEXT(), 'nullable': True, 'default': None, 'primary_key': 0}, {'name': 'Anos_empregado', 'type': BIGINT(), 'nullable': True, 'default': None, 'primary_key': 0}, {'name': 'Rendimento_anual', 'type': FLOAT(), 'nullable': True, 'default': None, 'primary_key': 0}, {'name': 'Tem_carro', 'type': BIGINT(), 'nullable': True, 'default': None, 'primary_key': 0}, {'name': 'Moradia', 'type': TEXT()

In [ ]:
# Visualizando a tabela criada
query = 'SELECT * FROM clientes'

pd.read_sql(query, engine)

ID_Cliente  Idade Grau_escolaridade   Estado_civil  Tamanho_familia  \
0          5008804     32   Ensino superior  União-estável                2   
1          5008805     32   Ensino superior  União-estável                2   
2          5008806     58      Ensino médio         Casado                2   
3          5008808     52      Ensino médio       Solteiro                1   
4          5008809     52      Ensino médio       Solteiro                1   
...            ...    ...               ...            ...              ...   
438458     6840104     62      Ensino médio     Divorciado                1   
438459     6840222     43      Ensino médio       Solteiro                1   
438460     6841878     22   Ensino superior       Solteiro                1   
438461     6842765     59      Ensino médio         Casado                2   
438462     6842885     51      Ensino médio         Casado                2   

         Categoria_de_renda          Ocupacao  Anos_empregado  \
0                 Empregado             Outro              12   
1                 Empregado             Outro              12   
2                 Empregado         Segurança               3   
3       Associado comercial            Vendas               8   
4       Associado comercial            Vendas               8   
...                     ...               ...             ...   
438458          Pensionista             Outro               0   
438459            Empregado  Construção Civil               8   
438460  Associado comercial            Vendas               1   
438461          Pensionista             Outro               0   
438462            Empregado            Vendas               3   

        Rendimento_anual  Tem_carro                   Moradia  
0               427500.0          1       Apartamento alugado  
1               427500.0          1       Apartamento alugado  
2               112500.0          1  Casa/apartamento próprio  
3               270000.0          0  Casa/apartamento próprio  
4               270000.0          0  Casa/apartamento próprio  
...                  ...        ...                       ...  
438458          135000.0          0  Casa/apartamento próprio  
438459          103500.0          0  Casa/apartamento próprio  
438460           54000.0          0          Mora com os pais  
438461           72000.0          0  Casa/apartamento próprio  
438462          121500.0          0  Casa/apartamento próprio  

[438463 rows x 11 columns]

## Realizando alterações no banco de dados:
1a) Alteração: \
Atualizar o registro do cliente de ID 6840104 que teve o rendimento anual alterado para 300000.

In [ ]:
# importando o método text
from sqlalchemy import text

In [ ]:
# Criando a consulta que irá realizar a atualização
query = 'UPDATE clientes SET Rendimento_anual = 300000 WHERE ID_Cliente = 6840104'

# Abrindo uma conexão com o banco de dados para realizar a consulta
with engine.connect() as conn:
  # executando a consulta
  result = conn.execute(text(query))
  # confirmando a consulta
  conn.commit()

In [ ]:
# Visualizando a linha alterada
query = 'SELECT * FROM clientes WHERE ID_Cliente = 6840104'

pd.read_sql(query, engine)

ID_Cliente  Idade Grau_escolaridade Estado_civil  Tamanho_familia  \
0     6840104     62      Ensino médio   Divorciado                1   

  Categoria_de_renda Ocupacao  Anos_empregado  Rendimento_anual  Tem_carro  \
0        Pensionista    Outro               0          300000.0          0   

                    Moradia  
0  Casa/apartamento próprio

2a) Alteração: \
Excluir o registro do cliente de ID 5008809, pois essa pessoa não possui mais conta na instituição financeira.

In [ ]:
query = 'DELETE FROM clientes WHERE ID_Cliente = 5008809'

# Abrindo uma conexão com o banco de dados para realizar a consulta
with engine.connect() as conn:
  # executando a consulta
  result = conn.execute(text(query))
  # confirmando a consulta
  conn.commit()

query = 'SELECT * FROM clientes'
pd.read_sql(query, engine)

ID_Cliente  Idade Grau_escolaridade   Estado_civil  Tamanho_familia  \
0          5008804     32   Ensino superior  União-estável                2   
1          5008805     32   Ensino superior  União-estável                2   
2          5008806     58      Ensino médio         Casado                2   
3          5008808     52      Ensino médio       Solteiro                1   
4          5008810     52      Ensino médio       Solteiro                1   
...            ...    ...               ...            ...              ...   
438457     6840104     62      Ensino médio     Divorciado                1   
438458     6840222     43      Ensino médio       Solteiro                1   
438459     6841878     22   Ensino superior       Solteiro                1   
438460     6842765     59      Ensino médio         Casado                2   
438461     6842885     51      Ensino médio         Casado                2   

         Categoria_de_renda          Ocupacao  Anos_empregado  \
0                 Empregado             Outro              12   
1                 Empregado             Outro              12   
2                 Empregado         Segurança               3   
3       Associado comercial            Vendas               8   
4       Associado comercial            Vendas               8   
...                     ...               ...             ...   
438457          Pensionista             Outro               0   
438458            Empregado  Construção Civil               8   
438459  Associado comercial            Vendas               1   
438460          Pensionista             Outro               0   
438461            Empregado            Vendas               3   

        Rendimento_anual  Tem_carro                   Moradia  
0               427500.0          1       Apartamento alugado  
1               427500.0          1       Apartamento alugado  
2               112500.0          1  Casa/apartamento próprio  
3               270000.0          0  Casa/apartamento próprio  
4               270000.0          0  Casa/apartamento próprio  
...                  ...        ...                       ...  
438457          300000.0          0  Casa/apartamento próprio  
438458          103500.0          0  Casa/apartamento próprio  
438459           54000.0          0          Mora com os pais  
438460           72000.0          0  Casa/apartamento próprio  
438461          121500.0          0  Casa/apartamento próprio  

[438462 rows x 11 columns]

3a) Alteração: \
Criar um novo registro de cliente seguindo as especificações abaixo: \
ID_Cliente: 6850985 \
Idade: 33 \
Grau_escolaridade: Doutorado \
Estado_civil: Solteiro \
Tamanho_familia: 1 \
Categoria_de_renda: Empregado \
Ocupacao: TI \
Anos_empregado: 2 \
Rendimento_anual: 290000 \
Tem_carro: 0 \
Moradia: Casa/apartamento próprio

In [ ]:
query = 'INSERT INTO clientes (ID_Cliente, Idade, Grau_escolaridade, Estado_civil, Tamanho_familia, Categoria_de_renda, Ocupacao, Anos_empregado, Rendimento_anual, Tem_carro, Moradia) VALUES (6850985, 33, "Doutorado", "Solteiro", 1, "Empregado", "TI", 2, 290000, 0, "Casa/apartamento próprio")'

# Abrindo uma conexão com o banco de dados para realizar a consulta
with engine.connect() as conn:
  # executando a consulta
  result = conn.execute(text(query))
  # confirmando a consulta
  conn.commit()

In [ ]:
query = 'SELECT * FROM clientes'
pd.read_sql(query, engine).tail()

ID_Cliente  Idade Grau_escolaridade Estado_civil  Tamanho_familia  \
438458     6840222     43      Ensino médio     Solteiro                1   
438459     6841878     22   Ensino superior     Solteiro                1   
438460     6842765     59      Ensino médio       Casado                2   
438461     6842885     51      Ensino médio       Casado                2   
438462     6850985     33         Doutorado     Solteiro                1   

         Categoria_de_renda          Ocupacao  Anos_empregado  \
438458            Empregado  Construção Civil               8   
438459  Associado comercial            Vendas               1   
438460          Pensionista             Outro               0   
438461            Empregado            Vendas               3   
438462            Empregado                TI               2   

        Rendimento_anual  Tem_carro                   Moradia  
438458          103500.0          0  Casa/apartamento próprio  
438459           54000.0          0          Mora com os pais  
438460           72000.0          0  Casa/apartamento próprio  
438461          121500.0          0  Casa/apartamento próprio  
438462          290000.0          0  Casa/apartamento próprio